NUMPY assingment

In [92]:
import numpy as np
import pandas as pd
import random
import sys

In [2]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr1= np.array([1,2,3,4,5])
type(arr1), arr1

(numpy.ndarray, array([1, 2, 3, 4, 5]))

In [3]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
type(arr[0])

numpy.float64

In [4]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([2+3j, 4+2j, 3+7j], dtype=np.complex128)
type(arr[1])


numpy.complex128

In [5]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr1= np.array([1,2,3,4,5], dtype=np.float32)
type(arr1[1])

numpy.float32

In [6]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.5, 2.6, 3.7], dtype=np.float32)
type(arr[1])

numpy.float32

In [7]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    attributes = {
        'shape': arr.shape,
        'size': arr.size,
        'dtype': arr.dtype
    }
    return attributes

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))

{'shape': (2, 2), 'size': 4, 'dtype': dtype('int32')}


In [8]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    dimension = arr.ndim
    return f"The Array dimension is: {dimension}"


arr = np.array([[[1, 2], [3, 4]]])
print(array_dimension(arr))

The Array dimension is: 3


In [9]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    attributes = {
        'item': arr.item,
        'size': arr.size,
        'info': arr.info
    }
    return attributes

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))

{'shape': (2, 2), 'size': 4, 'dtype': dtype('int32')}


In [10]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2], [3, 4]])
print(array_strides(arr))

(8, 4)


In [11]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return {
        'shape': arr.shape,
        'strides': arr.strides
    }

arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))

{'shape': (2, 2), 'strides': (8, 4)}


In [3]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

n = 10
print(create_zeros_array(n))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
#NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(r,c):
    return np.ones((r,c))

r = 3
c = 4
print(create_ones_matrix(r,c))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start , stop, step):
    return np.arange(start , stop, step)

start = 1
stop = 100
step = 5

print(generate_range_array(start , stop, step))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [16]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 0.0
stop = 5.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print(linear_space)

[0.   1.25 2.5  3.75 5.  ]


In [17]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
#identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

def numpy_array(a):
    return np.array(a)

a = [1, 2, 3, 4, 5]
array1 = numpy_array(a)
print(type(array1))


<class 'numpy.ndarray'>


In [20]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

normal_array = np.array([1,2,3,4,5])
new_array_view = normal_array.view()

print("Original Array:", normal_array)
print("New Array View:", new_array_view)

Original Array: [1 2 3 4 5]
New Array View: [1 2 3 4 5]


In [6]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenates_arrays(a1,a2, axis =0):
    return np.concatenate((a1,a2), axis= axis)
 

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

array_axis0 = concatenates_arrays(a1, a2, axis=0)
print("Concatenated along axis 0:\n", array_axis0)

array_axis1 = concatenates_arrays(a1, a2, axis=1)
print("Concatenated along axis 1:\n", array_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [24]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

a1 = np.array([[1, 2, 3], [4, 5, 6]])  
a2 = np.array([[7], [8]])              

concatenated_array = np.concatenate((a1, a2), axis=1)

print("Array 1:\n", a1)
print("Array 2:\n", a2)
print("Concatenated Array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[7]
 [8]]
Concatenated Array:
 [[1 2 3 7]
 [4 5 6 8]]


In [25]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arrays):
    return np.vstack(arrays)

a1 = np.array([[1, 2, 3]])
a2 = np.array([[4, 5, 6]])
a3 = np.array([[7, 8, 9]])

stacked_array = vertical_stack([a1, a2, a3])

print("Vertically Stacked Array:\n", stacked_array)


Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
"""21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size."""

def create_integer_range(start, stop, step):
    return np.arange(start, stop + 1, step)

start = 0
stop = 20
step = 4
integer_range_array = create_integer_range(start, stop, step)
print("Integer Range Array:", integer_range_array)


Integer Range Array: [ 0  4  8 12 16 20]


In [27]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def g_e_s_v():
    return np.linspace(0, 1, 10)

equally_spaced_values = g_e_s_v()
print("Equally Spaced Values:", equally_spaced_values)

Equally Spaced Values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [31]:

#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def glsv():
    return np.logspace(0,3,5)

lsv = glsv()
print("Logarithmically Spaced Values:", lsv)


Logarithmically Spaced Values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [33]:
"""24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100."""

data_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data_array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       38       96       49
1       76       13       61
2       39       41       35
3       46       36        7
4       83       71        1


In [41]:
"""25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame."""

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [1, -2, 3, -4, 5],'B': [10, 20, -30, 40, -50]}
df = pd.DataFrame(data)

print("Original DataFrame:\n",(df))

df_modified = replace_negatives_with_zeros(df, 'B')

print("\nDataFrame with Negative Values Replaced by Zeros:\n",(df_modified))

Original DataFrame:
    A   B
0  1  10
1 -2  20
2  3 -30
3 -4  40
4  5 -50

DataFrame with Negative Values Replaced by Zeros:
    A   B
0  1  10
1 -2  20
2  3   0
3 -4  40
4  5   0


In [42]:
#26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

print(arr[3])

40


In [45]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

element_12 = arr_2d[1, 2]

print("Element at index (1, 2):", element_12)


Element at index (1, 2): 6


In [51]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])

mask = arr > 5 

elements_greater_than_5 = arr[mask]
print("elements greater than 5 is :",elements_greater_than_5)

elements greater than 5 is : [ 8 10  7]


In [54]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

slicing_arr1 = arr[2:5]
slicing_arr1

array([3, 4, 5])

In [76]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2,1:3]

sub_array

array([[2, 3],
       [5, 6]])

In [78]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

#function
def extract_elements_by_indices(arr_2d, indices):
    flat_arr = arr_2d.flatten()
    extracted_elements = flat_arr[indices]
    return extracted_elements

#inputs
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],])

indices = np.array([1, 4, 7])

#function coll
extracted_elements = extract_elements_by_indices(arr_2d, indices)

#result
extracted_elements

array([2, 5, 8])

In [81]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

#function
def filters_elements_greater_than_a_threshold(arr,threshold):
     mask = arr > threshold
     filtered_array = arr[mask]
     return filtered_array

#inputs
arr = np.array([1,2,3,4,5,6,7,8,9,11,34,56,23,78,90])
threshold = 20

#function call
filters_elements = filters_elements_greater_than_a_threshold(arr,threshold)

#result
filters_elements

array([34, 56, 23, 78, 90])

In [93]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

#function
def extract_elements_3d(arr_3d, d1, d2, d3):
    extracted_elements = arr_3d[d1, d2, d3]
    return extracted_elements

#input
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                    [[7, 8, 9],
                    [10, 11, 12]]])

d1 = np.array([0,1])
d2 = np.array([1,1])
d3 = np.array([2,1])

#function call
extract_elements = extract_elements_3d(arr_3d, d1, d2, d3)

#result
extract_elements

array([ 6, 11])

In [99]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

#function
def filter_with_conditions(arr, con1, con2):
    filtered_elements = arr[np.logical_and(con1, con2)]
    return filtered_elements

#input
arr = np.array([11,22,33,44,55,66,77,88,99])
con1 = arr < 50
con2 =  arr / 11

#function call
satisfied_condition_element = filter_with_conditions(arr, con1, con2)

#result
satisfied_condition_element

array([11, 22, 33, 44])

In [100]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

#function
def e_e(arr_2d, row, col):
    extracted_elements = arr_2d[row , col]
    return extracted_elements

# inputs
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

row = np.array([0, 1, 2])
col = np.array([1, 2, 0])

#function coll
the_elements = e_e(arr_2d, row, col)

#result
the_elements

array([2, 6, 7])

In [104]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

result = arr + 5

print("original array : \n", arr)
print("broadcasting arry : \n", result)

original array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
broadcasting arry : 
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [3]:
"""37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting."""

arr1 = np.array([1,2,3])
arr2 = np.array([[4,5,6,7],
                 [8,9,10,11],
                 [12,13,14,15]])

arr1_reshaped = arr1.reshape(3, 1)
new_array = arr2 * arr1_reshaped

new_array

array([[ 4,  5,  6,  7],
       [16, 18, 20, 22],
       [36, 39, 42, 45]])

In [4]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]]) 
arr2 = np.array([[5, 6, 7],[8, 9, 10],[11, 12, 13],[14, 15, 16]])

arr1_re = arr1.reshape(4, 1)
new_array = arr2 + arr1_re

new_array

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [5]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])  
arr2 = np.array([[4, 5, 6]])

new = arr1 + arr2

new

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [8]:
"""40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility."""

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

#maching the array shape
arr1_re = arr1[:, :, np.newaxis]  
arr2_re = arr2[:, np.newaxis, :]  

result = arr1_re * arr2_re

result

array([[[ 7,  8],
        [14, 16],
        [21, 24]],

       [[36, 40],
        [45, 50],
        [54, 60]]])

In [11]:
#41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

c_mean = np.mean(arr, axis=0)

c_mean

array([2.5, 3.5, 4.5])

In [12]:
#42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

r_max = np.max(arr, axis=1)

r_max

array([3, 6])

In [15]:
#43. For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

col_max_indices = np.argmax(arr, axis=0)

col_max_indices

array([1, 1, 1], dtype=int64)

In [20]:
#44. For the given array, apply custom function to calculate moving sum along rows.

arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr, window_size):
    result = np.convolve(arr, np.ones(window_size), 'valid')
    return result

window_size = 3
moving = np.apply_along_axis(moving_sum, axis=1, arr=arr, window_size=window_size)

moving

array([[ 6.],
       [15.]])

In [24]:
#45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

all_even = np.all(arr % 2 == 0, axis=0)

all_even

array([False, False, False])

In [29]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

oa = np.array([1, 2, 3, 4, 5, 6])

def reshape_array(arr, m, n):
    rm = np.reshape(arr, (m, n))
    return rm

m = 2
n = 3

reshaped = reshape_array(oa, m, n)

reshaped 

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#47. Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_matrix(input_m):
    fa = input_m.flatten()
    return fa

flattened_a = flatten_matrix(input_matrix)

flattened_a

array([1, 2, 3, 4, 5, 6])

In [32]:
#48. Write a function that concatenates two given arrays along a specified axis.

def concatenates_arrays(a1,a2, axis =0):
    return np.concatenate((a1,a2), axis= axis)
 

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

array_axis0 = concatenates_arrays(a1, a2, axis=0)
print("Concatenated along axis 0:\n", array_axis0) # 0

array_axis1 = concatenates_arrays(array1, array2, axis=1) #axis 1
print("Concatenated along axis 1:\n", array_axis1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [36]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(original_array, axis, num_splits):
    sub_arrays = np.split(original_array, num_splits, axis=axis)
    return sub_arrays

axis = 1  
num_splits = 3

sub_arrays = split_array(original_array, axis, num_splits)

for i in sub_arrays:
    print("array are : \n", i)


array are : 
 [[1]
 [4]
 [7]]
array are : 
 [[2]
 [5]
 [8]]
array are : 
 [[3]
 [6]
 [9]]


In [40]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

def insert_and_delete_elements(array, i_insert, v_insert, i_delete):
    for idx, val in zip(i_insert, v_insert):
        array = np.insert(array, idx, val)
    
    array = np.delete(array, i_delete)
    
    return array

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

result_array

array([ 1, 10, 11,  4,  5])

In [19]:
"""51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`."""


arr1 = np.random.randint(1,10, size=(3,3))
arr2 = np.arange(1, 10).reshape(3, 3)

result = arr1 + arr2

print("arr1 :\n",arr1)
print("arr2 :\n",arr2)
print("element-wise addition result \n:", result)


arr1 :
 [[4 2 1]
 [9 4 4]
 [3 5 1]]
arr2 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
element-wise addition result 
: [[ 5  4  4]
 [13  9 10]
 [10 13 10]]


In [20]:
"""52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise."""

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1 :\n", arr1)
print("arr2 :\n", arr2)
print("Subtract array is :\n", result)

arr1 :
 [10  9  8  7  6  5  4  3  2  1]
arr2 :
 [ 1  2  3  4  5  6  7  8  9 10]
Subtract array is :
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [22]:
"""53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`."""

arr1 = np.random.randint(0, 10, size=(3, 5))
arr2 = np.arange(1, 6)

result = arr1 * arr2

print("arr1 :\n", arr1)
print("arr2 :\n", arr2)
print("multiply array is :\n", result)

arr1 :
 [[6 0 8 7 9]
 [5 9 6 3 1]
 [0 8 3 7 6]]
arr2 :
 [1 2 3 4 5]
multiply array is :
 [[ 6  0 24 28 45]
 [ 5 18 18 12  5]
 [ 0 16  9 28 30]]


In [23]:
"""54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5, Perform element-wise division of `arr1` by `arr2`."""

arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)

result = arr1 / arr2

print("arr1  :\n", arr1)
print("arr2 : \n", arr2)
print("element-wise division result is : \n", result)

arr1  :
 [ 2  4  6  8 10]
arr2 : 
 [1 2 3 4 5]
element-wise division result is : 
 [2. 2. 2. 2. 2.]


In [24]:
"""55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise."""

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]

result = np.power(arr1, arr2)

print("arr1  :\n", arr1)
print("arr2 : \n", arr2)
print("raised to the power of `arr2` element-wise : \n", result)

arr1  :
 [1 2 3 4 5]
arr2 : 
 [5 4 3 2 1]
raised to the power of `arr2` element-wise : 
 [ 1 16 27 16  5]


In [25]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def csc(arr, substring):
    count = np.char.count(arr, substring).sum()
    return count

substring = 'hello'
count = csc(arr, substring)

print(f"The substring '{substring}' occurs {count} times in the array.")

The substring 'hello' occurs 3 times in the array.


In [28]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    joined_strings = ''.join(arr)
    uppercase_chars = ''.join([char for char in joined_strings if char.isupper()])
    return uppercase_chars

print("extracts uppercase characters is :\n",result)

extracts uppercase characters is :
 ['H' 'W' 'OAI' 'GPT']


In [29]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace occurrences of old_substring with new_substring
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

old_substring = 'apple'
new_substring = 'orange'

replaced_arr = replace_substring(arr, old_substring, new_substring)

replaced_arr

array(['orange', 'banana', 'grape', 'pineorange'], dtype='<U10')

In [30]:
#59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concatenate_strings(arr1, arr2):
    concatenated_arr = np.char.add(arr1, arr2)
    return concatenated_arr

concatenated_arr = concatenate_strings(arr1, arr2)

print("Array 1:\n",arr1)
print("\nArray 2:\n", arr2)
print("\nArray after concatenation:\n",concatenated_arr)


Array 1:
 ['Hello' 'World']

Array 2:
 ['Open' 'AI']

Array after concatenation:
 ['HelloOpen' 'WorldAI']


In [31]:
#60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):
    lengths = np.vectorize(len)(arr)
    return np.max(lengths)

longest_length = longest_string_length(arr)

print("Length of the longest string:\n", longest_length)

Length of the longest string:
 9


In [39]:
"""61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions."""

data = np.random.randint(1,1000, size= 100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print("dataset :", data)
print("")
print("mean :",mean)
print("median :", median)
print("variance : ", variance)
print("std_deviation :",std_deviation)

dataset : [ 85 479 510 702  61 876 115  59 789 258  59 473 629 654 155 332 385 657
  94 771 856 703 750 568 704  38 918 733 759 492 198 544 882 608 466 948
 757 605 761 646 391 933 951 584 365 148 686 452 360 669 463 830 484 741
  40 120 510 235 846 722 257 205  22 888 318 478 375  38 331 308 156 454
 654 822 489  26 183  16 387 519 982 110  58 216 611 847 837 703 427 701
 796  29 159 450 577 558 403 653  59 957]

mean : 486.68
median : 490.5
variance :  80211.0576
std_deviation : 283.21556736874476


In [49]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

data = np.random.randint(1,100, size= 50)

a = np.percentile(data, 25)
b = np.percentile(data, 75)

print("datset :\n",data)
print("")
print("25th percentiles :",a)
print("75th percentiles :",b)

datset :
 [95 93 27 15 68 40 82 19 78 68 94 30 32 52  2 34 65  4 46 45 86 66 43 75
 61 45 41 99 95 85 63  5 75 62 88 29 69 83 96 40 16  7 83 51 71 76 84  6
 59 57]

25th percentiles : 35.5
75th percentiles : 81.0


In [53]:
"""63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function."""

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

corr_coef = np.corrcoef(arr1, arr2)[0,1]

print("1st array",arr1)
print("2nd array",arr2)
print("correlation coefficient is :",corr_coef)

1st array [1 2 3 4 5]
2nd array [5 4 3 2 1]
correlation coefficient is : -0.9999999999999999


In [62]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

m1 = np.array([[1,2,3,4],[9,9,1,1]])
m2 = np.array([[1,2],[11,11],[5,6],[1,2]])

result = np.dot(m1,m2)

print("1st matrix :\n",m1)
print("2nd matrix :\n",m2)
print("matrix multiplication result :", result)

1st matrix :
 [[1 2 3 4]
 [9 9 1 1]]
2nd matrix :
 [[ 1  2]
 [11 11]
 [ 5  6]
 [ 1  2]]
matrix multiplication result : [[ 42  50]
 [114 125]]


In [70]:
"""65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles."""

data = np.random.randint(10,1000, size= 50)

a = np.percentile(data, 10)
b = np.percentile(data, 50)
c = np.percentile(data,90)
d = np.quantile(data,1)
e = np.quantile(data,0)

print("datset :\n",data)
print("")
print("10th percentiles :",a)
print("50th percentiles :",b)
print("90th percentiles :",c)
print("")
print("1st and 3rd quartiles valu are",d,e)

datset :
 [114 569 918 305 880 819 454 329 129 884 511 384 191 301 963 793  66 184
 298 962 790 758 667 526 981  59 962 532 737 320 234 692 586 969 995 795
 285 781 703 666 986  68 439 750 309  80 626 122 390 562]

10th percentiles : 121.2
50th percentiles : 565.5
90th percentiles : 962.1

1st and 3rd quartiles valu are 995 59


In [76]:
#66. Create a NumPy array of integers and find the index of a specific element.

array = np.array([1,2,3,4,5])

find = 3

index = np.where(array == find)

if len(index) > 0:
    print(f"The element {find} is found at index {index[0]}")

#only for not found the element
else:
    print(f"The element {find} is not found in the array.")

The element 3 is found at index [2]


In [79]:
#67. Generate a random NumPy array and sort it in ascending order.

arr = np.random.randint(1,100, size = 20)

sorted_array = np.sort(arr)

print("original array :", arr)
print("")
print("sorted array :", sorted_array)

original array : [30 80 83 16 39 59 81 67 14 76 15 44 41 28 80 92 32 50 35 13]

sorted array : [13 14 15 16 28 30 32 35 39 41 44 50 59 67 76 80 80 81 83 92]


In [80]:
#68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]

print("original array :", arr)
print("filter array is :", filtered_arr)


original array : [12 25  6 42  8 30]
filter array is : [25 42 30]


In [82]:
#69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]

print("original array :", arr)
print("filter array is :", filtered_arr)

original array : [ 1  5  8 12 15]
filter array is : [12 15]


In [85]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

filtered_arr =  arr[(arr >= 20) & (arr <= 40)]

print("original array :", arr)
print("filter array is :", filtered_arr)

original array : [10 20 30 40 50]
filter array is : [20 30 40]


In [86]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("original array :", arr)
print("byte order :", byte_order)

original array : [1 2 3]
byte order : =


In [87]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

arr = np.array([1, 2, 3], dtype=np.int32)
print("original array", arr)

arr.byteswap(True)
print("Array after byte swapping:", arr)

original array [1 2 3]
Array after byte swapping: [16777216 33554432 50331648]


In [88]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
print("oreginal array", arr)

arr_swapped = arr.newbyteorder()
print("after swapped", arr_swapped)

oreginal array [1 2 3]
after swapped [16777216 33554432 50331648]


In [93]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

system_byteorder = sys.byteorder

if system_byteorder == 'little':
    arr_swapped = arr.newbyteorder('big')
else:
    arr_swapped = arr.newbyteorder('little')

print("Original array:", arr)
print("\nArray with swapped byte order based on system endianness:",arr_swapped)

Original array: [1 2 3]

Array with swapped byte order based on system endianness: [16777216 33554432 50331648]


In [89]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    print("No byte swapping needed (native byte order)")
else:
    print(f"Byte swapping needed from {arr.dtype.byteorder} to {'>' if arr.dtype.byteorder == '<' else '<'}")

No byte swapping needed (native byte order)


In [99]:
"""76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`."""

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()
copy_arr[0] = 99

print("Original array (arr1):",arr1)
print("Modified copy (copy_arr):",copy_arr)

Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]

Modified copy (copy_arr): [99  2  3  4  5  6  7  8  9 10]


In [100]:
"""77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`."""

matrix = np.random.randint(0, 10, (3, 3))

view_slice = matrix[1:, 1:]

view_slice[0, 0] = 99

print("Original matrix after modifying view_slice:", matrix)
print("View slice:",view_slice)

Original matrix after modifying view_slice: [[ 6  1  3]
 [ 9 99  3]
 [ 6  7  7]]

View slice: [[99  3]
 [ 7  7]]


In [101]:
"""78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`."""

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, 1:3]

view_b += 5

print("Original array (array_a) after modifying view_b:",array_a)
print("View slice (view_b):",view_b)

Original array (array_a) after modifying view_b: [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]

View slice (view_b): [[10 11]
 [13 14]]


In [ ]:
"""79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`."""

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 99

print("Original array (orig_array) after modifying reshaped_view:",orig_array)
print("\nReshaped view (reshaped_view):",reshaped_view)

In [102]:
"""80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`."""

data = np.random.randint(0, 10, (3, 4))

data_copy = data[data > 5].copy()

if data_copy.size > 0: 
    data_copy[0] = 99

print("Original array (data):",data)
print("\nModified copy of elements greater than 5 (data_copy):",data_copy)

Original array (data): [[4 3 1 0]
 [1 3 6 5]
 [0 5 1 1]]

Modified copy of elements greater than 5 (data_copy): [99]


In [98]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

addition_result = np.add(A, B)

subtraction_result = np.subtract(A, B)

print("Matrix A:",A)
print("\nMatrix B:",B)
print("\nResult of addition (A + B):",addition_result)
print("\nResult of subtraction (A - B):",subtraction_result)


Matrix A: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B: [[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of addition (A + B): [[10 10 10]
 [10 10 10]
 [10 10 10]]

Result of subtraction (A - B): [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [97]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

result = np.dot(C, D)

print("Matrix C:",C)
print("\nMatrix D:",D)
print("\nResult of matrix multiplication C * D:",result)


Matrix C: [[1 2]
 [3 4]
 [5 6]]

Matrix D: [[ 7  8  9 10]
 [11 12 13 14]]

Result of matrix multiplication C * D: [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [96]:
#83. Create a matrix `E` and find its transpose.

E = np.array([[1, 2, 3],
              [4, 5, 6]])

E_transpose = E.T

print("Matrix E:", E)
print("\nTranspose of matrix E:",E_transpose)

Matrix E: [[1 2 3]
 [4 5 6]]

Transpose of matrix E: [[1 4]
 [2 5]
 [3 6]]


In [95]:
#84. Generate a square matrix `F` and compute its determinant.

F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

det_F = np.linalg.det(F)

print("Matrix F:",F)
print("\nDeterminant of matrix F:", det_F)

Matrix F: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


In [94]:
#85. Create a square matrix `G` and find its inverse.

G = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

G_inv = np.linalg.inv(G)

print("Matrix G:", G)
print("\nInverse of matrix G:",G_inv)

Matrix G: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Inverse of matrix G: [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
