NUMPY assingment

In [2]:
import numpy as np
import pandas as pd

In [2]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
arr1= np.array([1,2,3,4,5])
type(arr1), arr1

(numpy.ndarray, array([1, 2, 3, 4, 5]))

In [3]:
#2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
type(arr[0])

numpy.float64

In [4]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([2+3j, 4+2j, 3+7j], dtype=np.complex128)
type(arr[1])


numpy.complex128

In [5]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr1= np.array([1,2,3,4,5], dtype=np.float32)
type(arr1[1])

numpy.float32

In [6]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.5, 2.6, 3.7], dtype=np.float32)
type(arr[1])

numpy.float32

In [7]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

def array_attributes(arr):
    attributes = {
        'shape': arr.shape,
        'size': arr.size,
        'dtype': arr.dtype
    }
    return attributes

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))

{'shape': (2, 2), 'size': 4, 'dtype': dtype('int32')}


In [8]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    dimension = arr.ndim
    return f"The Array dimension is: {dimension}"


arr = np.array([[[1, 2], [3, 4]]])
print(array_dimension(arr))

The Array dimension is: 3


In [9]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    attributes = {
        'item': arr.item,
        'size': arr.size,
        'info': arr.info
    }
    return attributes

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))

{'shape': (2, 2), 'size': 4, 'dtype': dtype('int32')}


In [10]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2], [3, 4]])
print(array_strides(arr))

(8, 4)


In [11]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return {
        'shape': arr.shape,
        'strides': arr.strides
    }

arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))

{'shape': (2, 2), 'strides': (8, 4)}


In [3]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

n = 10
print(create_zeros_array(n))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
#NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(r,c):
    return np.ones((r,c))

r = 3
c = 4
print(create_ones_matrix(r,c))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start , stop, step):
    return np.arange(start , stop, step)

start = 1
stop = 100
step = 5

print(generate_range_array(start , stop, step))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [16]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = 0.0
stop = 5.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print(linear_space)

[0.   1.25 2.5  3.75 5.  ]


In [17]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
#identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

def numpy_array(a):
    return np.array(a)

a = [1, 2, 3, 4, 5]
array1 = numpy_array(a)
print(type(array1))


<class 'numpy.ndarray'>


In [20]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

normal_array = np.array([1,2,3,4,5])
new_array_view = normal_array.view()

print("Original Array:", normal_array)
print("New Array View:", new_array_view)

Original Array: [1 2 3 4 5]
New Array View: [1 2 3 4 5]


In [23]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenates_arrays(a1,a2, axis =0):
    return np.concatenate((a1,a2), axis= axis)

a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

array_axis0 = concatenates_arrays(a1, a2, axis=0)
print("Concatenated along axis 0:\n", array_axis0)

array_axis1 = concatenates_arrays(a1, a2, axis=1)
print("Concatenated along axis 1:\n", array_axis1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [24]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

a1 = np.array([[1, 2, 3], [4, 5, 6]])  
a2 = np.array([[7], [8]])              

concatenated_array = np.concatenate((a1, a2), axis=1)

print("Array 1:\n", a1)
print("Array 2:\n", a2)
print("Concatenated Array:\n", concatenated_array)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[7]
 [8]]
Concatenated Array:
 [[1 2 3 7]
 [4 5 6 8]]


In [25]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arrays):
    return np.vstack(arrays)

a1 = np.array([[1, 2, 3]])
a2 = np.array([[4, 5, 6]])
a3 = np.array([[7, 8, 9]])

stacked_array = vertical_stack([a1, a2, a3])

print("Vertically Stacked Array:\n", stacked_array)


Vertically Stacked Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
"""21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size."""

def create_integer_range(start, stop, step):
    return np.arange(start, stop + 1, step)

start = 0
stop = 20
step = 4
integer_range_array = create_integer_range(start, stop, step)
print("Integer Range Array:", integer_range_array)


Integer Range Array: [ 0  4  8 12 16 20]


In [27]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def g_e_s_v():
    return np.linspace(0, 1, 10)

equally_spaced_values = g_e_s_v()
print("Equally Spaced Values:", equally_spaced_values)

Equally Spaced Values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [31]:

#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def glsv():
    return np.logspace(0,3,5)

lsv = glsv()
print("Logarithmically Spaced Values:", lsv)


Logarithmically Spaced Values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [33]:
"""24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100."""

data_array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data_array, columns=['Column1', 'Column2', 'Column3'])

print("Pandas DataFrame:")
print(df)


Pandas DataFrame:
   Column1  Column2  Column3
0       38       96       49
1       76       13       61
2       39       41       35
3       46       36        7
4       83       71        1


In [41]:
"""25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame."""

def replace_negatives_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {'A': [1, -2, 3, -4, 5],'B': [10, 20, -30, 40, -50]}
df = pd.DataFrame(data)

print("Original DataFrame:\n",(df))

df_modified = replace_negatives_with_zeros(df, 'B')

print("\nDataFrame with Negative Values Replaced by Zeros:\n",(df_modified))

Original DataFrame:
    A   B
0  1  10
1 -2  20
2  3 -30
3 -4  40
4  5 -50

DataFrame with Negative Values Replaced by Zeros:
    A   B
0  1  10
1 -2  20
2  3   0
3 -4  40
4  5   0


In [42]:
#26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

print(arr[3])

40


In [45]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

element_12 = arr_2d[1, 2]

print("Element at index (1, 2):", element_12)


Element at index (1, 2): 6


In [51]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])

mask = arr > 5 

elements_greater_than_5 = arr[mask]
print("elements greater than 5 is :",elements_greater_than_5)

elements greater than 5 is : [ 8 10  7]


In [54]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

slicing_arr1 = arr[2:5]
slicing_arr1

array([3, 4, 5])

In [76]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2,1:3]

sub_array

array([[2, 3],
       [5, 6]])

In [78]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

#function
def extract_elements_by_indices(arr_2d, indices):
    flat_arr = arr_2d.flatten()
    extracted_elements = flat_arr[indices]
    return extracted_elements

#inputs
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],])

indices = np.array([1, 4, 7])

#function coll
extracted_elements = extract_elements_by_indices(arr_2d, indices)

#result
extracted_elements

array([2, 5, 8])

In [81]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

#function
def filters_elements_greater_than_a_threshold(arr,threshold):
     mask = arr > threshold
     filtered_array = arr[mask]
     return filtered_array

#inputs
arr = np.array([1,2,3,4,5,6,7,8,9,11,34,56,23,78,90])
threshold = 20

#function call
filters_elements = filters_elements_greater_than_a_threshold(arr,threshold)

#result
filters_elements

array([34, 56, 23, 78, 90])

In [93]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

#function
def extract_elements_3d(arr_3d, d1, d2, d3):
    extracted_elements = arr_3d[d1, d2, d3]
    return extracted_elements

#input
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                    [[7, 8, 9],
                    [10, 11, 12]]])

d1 = np.array([0,1])
d2 = np.array([1,1])
d3 = np.array([2,1])

#function call
extract_elements = extract_elements_3d(arr_3d, d1, d2, d3)

#result
extract_elements

array([ 6, 11])

In [99]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

#function
def filter_with_conditions(arr, con1, con2):
    filtered_elements = arr[np.logical_and(con1, con2)]
    return filtered_elements

#input
arr = np.array([11,22,33,44,55,66,77,88,99])
con1 = arr < 50
con2 =  arr / 11

#function call
satisfied_condition_element = filter_with_conditions(arr, con1, con2)

#result
satisfied_condition_element

array([11, 22, 33, 44])

In [100]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

#function
def e_e(arr_2d, row, col):
    extracted_elements = arr_2d[row , col]
    return extracted_elements

# inputs
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

row = np.array([0, 1, 2])
col = np.array([1, 2, 0])

#function coll
the_elements = e_e(arr_2d, row, col)

#result
the_elements

array([2, 6, 7])

In [104]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

result = arr + 5

print("original array : \n", arr)
print("broadcasting arry : \n", result)

original array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
broadcasting arry : 
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
"""37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting."""


In [ ]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.


In [ ]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.


In [ ]:
"""40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility."""